draw_config:
  append_colon_to_layer_header: true
  arc_radius: 6.0
  arc_scale: 1.0
  combo_h: 26.0
  combo_w: 28.0
  inner_pad_h: 2.0
  inner_pad_w: 2.0
  key_h: 56.0
  key_rx: 6.0
  key_ry: 6.0
  key_w: 60.0
  line_spacing: 1.2
  outer_pad_h: 56.0
  outer_pad_w: 30.0
  small_pad: 2.0
  split_gap: 30.0
  svg_style: |
    /* font and background color specifications */
    svg {
        font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 14px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: #24292e;
    }

    /* default key styling */
    rect {
        fill: #f6f8fa;
        stroke: #c9cccf;
        stroke-width: 1;
    }

    /* color accent for combo boxes */
    rect.combo {
        fill: #cdf;
    }

    /* color accent for held keys */
    rect.held, rect.combo.held {
        fill: #fdd;
    }

    /* color accent for ghost (optional) keys */
    rect.ghost, rect.combo.ghost {
        fill: #ddd;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    /* styling for layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        stroke: white;
        stroke-width: 2;
        paint-order: stroke;
    }

    /* styling for combo tap, and key hold/shifted label text */
    text.combo, text.hold, text.shifted {
        font-size: 11px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
    }

    /* styling for hold/shifted label text in combo box */
    text.combo.hold, text.combo.shifted {
        font-size: 8px;
    }

    /* styling for combo dendrons */
    path {
        stroke-width: 1;
        stroke: gray;
        fill: none;
    }
parse_config:
  assign_combos_to_layers: false
  preprocess: true
  qmk_keycode_map:
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    AT: '@'
    BACKSLASH: \
    BSLS: \
    CIRC: ^
    CIRCUMFLEX: ^
    COLN: ':'
    COLON: ':'
    COMM: ','
    COMMA: ','
    DLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTE: '"'
    DQT: '"'
    DQUO: '"'
    EQL: '='
    EQUAL: '='
    EXCLAIM: '!'
    EXLM: '!'
    GRAVE: '`'
    GRV: '`'
    GT: '>'
    HASH: '#'
    LABK: <
    LBRC: '['
    LCBR: '{'
    LEFT_ANGLE_BRACKET: <
    LEFT_BRACKET: '['
    LEFT_CURLY_BRACE: '{'
    LEFT_PAREN: (
    LPRN: (
    LT: <
    MINS: '-'
    MINUS: '-'
    'NO': ''
    NONUS_HASH: '#'
    NUHS: '#'
    PERC: '%'
    PERCENT: '%'
    PIPE: '|'
    PLUS: +
    QUES: '?'
    QUESTION: '?'
    QUOT: ''''
    QUOTE: ''''
    RABK: '>'
    RBRC: ']'
    RCBR: '}'
    RIGHT_ANGLE_BRACKET: '>'
    RIGHT_BRACKET: ']'
    RIGHT_CURLY_BRACE: '}'
    RIGHT_PAREN: )
    RPRN: )
    SCLN: ;
    SEMICOLON: ;
    SLASH: /
    SLSH: /
    TILD: '~'
    TILDE: '~'
    TRANSPARENT: ''
    TRNS: ''
    UNDERSCORE: _
    UNDS: _
    SPACE: ⎵
  raw_binding_map:
    '&mm_grescm': {t: '⎋', s: '` ~'}
    '&mm_bspc_del': {t: '⌫', s: '⌦'}
    '&bspc_del': {t: '⌫', s: '⌦'}
    '&mm_grescm_gui': {t: ⎋, h: '$$material:menu_open$$', s: '~ `'}
    '&mm_spc_unds_layer': {t: '⎵', h: 'SYM', s: '_ -'}
    '&mm_plus_minus': {t: '+', s: '-'}
    '&mm_grave_caret': {t: '`', s: '^'}
    '&mm_bracket_r': {t: '(', s: ')'}
    '&mm_comma_semi_meh': {t: ',', s: ';', h: 'MEH'}
    '&mm_dot_colon': {t: '.', s: ':'}
    '&mm_none_undo': ''
    '&mm_left_word_cut': '↞'
    '&mm_up_save': '↑'
    '&mm_down_copy': '↓'
    '&mm_none_paste': ''
    '&mm_1_cut': '1'
    '&mm_2_copy': '2'
    '&mm_5_save': '5'
    '&swapper_cmd_tab': {t: '$$material:menu_open$$↹'}
    '&td_at_email': {t: '@'}
    '&num_word': 'NUM'
    '&nav_word': 'NAV'
    '&caps_word_capslock': "Caps\nWord"
    '&caps_word': '⇪'
    '&td_shift_l': '⇧'
    '&td_shift_r': '⇧'
    '&td_nav_layer': {t: '⏎', h: 'NAV'}
    '&td_bt_clear': 'BT CLR'
    '&m_type_md_code_block': '```'
    '&kt LSHFT': "⇧\nLock"
    '&lt_num_word 4 0': {t: "Num\nWord", h: 'Num'}
    '&ltog LGUI 5': {t: "Cancel\nNav", h: '$$material:menu_open$$'}
    '&ltog LGUI 6': {t: "Cancel\nNum", h: '$$material:menu_open$$'}
    '&ltog LGUI 7': {t: "Cancel\nSym", h: '$$material:menu_open$$'}
    '&ltog LGUI 8': {t: "Cancel\nFunc", h: '$$material:menu_open$$'}
    '&ltog LGUI 9': {t: "Cancel\nAdjust", h: '$$material:menu_open$$'}
    '&toggle_num': {t: "NUM", h: "TOG NUM"}
    '&toggle_nav': {t: "NAV", h: "TOG NAV"}
    '&plus_morph': {t: "+", s: "="}
  skip_binding_parsing: false
  zmk_keycode_map:
    AMPERSAND: '&'
    AMPS: '&'
    APOS: {t: "'", s: '"'}
    APOSTROPHE: <
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: {t: '\', s: '|'}
    BSLH: {t: '\', s: '|'}
    CARET: ^
    COLON: ':'
    COMMA: {t: ',', s: '<'}
    DLLR: $
    DOLLAR: $
    DOT: {t: '.', s: '>'}
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: {t: '=', s: '+'}
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: {t: '/', s: '?'}
    GRAVE: {t: '`', s: '~'}
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: {t: '[', s: '{'}
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: {t: '-', s: '_'}
    N0: {t: '0', s: ')'}
    N1: {t: '1', s: '!'}
    N2: {t: '2', s: '@'}
    N3: {t: '3', s: '#'}
    N4: {t: '4', s: '$'}
    N5: {t: '5', s: '%'}
    N6: {t: '6', s: '^'}
    N7: {t: '7', s: '&'}
    N8: {t: '8', s: '*'}
    N9: {t: '9', s: '('}
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: {t: ']', s: '}'}
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: {t: ';', s: ':'}
    SEMICOLON:  {t: ';', s: ':'}
    SINGLE_QUOTE:  {t: '''', s: '"'}
    SLASH: {t: '/', s: '?'}
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
    LCTRL: "CTRL"
    LALT: "ALT"
    LGUI: '$$material:menu_open$$'
    LSHFT: ⇧
    RCTRL: "CTRL"
    LEFT_CONTROL: "CTRL"
    LEFT_ALT: "ALT"
    LEFT_GUI: '$$material:menu_open$$'
    LEFT_SHFT: ⇧
    RALT: "ALT"
    RGUI: '$$material:menu_open$$'
    RSHFT: ⇧
    RIGHT_CONTROL: "CTRL"
    RIGHT_ALT: "ALT"
    RIGHT_GUI: '$$material:menu_open$$'
    RIGHT_SHFT: ⇧
    LEFT: ←
    RIGHT: →
    UP: ↑
    DOWN: ↓
    TAB: ↹
    RETURN: '⏎'
    ESCAPE: '⎋'
    C_REWIND: '⏮'
    C_FAST_FORWARD: '⏭'
    C_PAUSE: '⏯'
    C_MUTE: "VOL\nMUTE"
    C_VOLUME_DOWN: "VOL\nDOWN"
    C_VOLUME_UP: "VOL\nUP"
    C_BRIGHTNESS_DEC: '☀↓'
    C_BRIGHTNESS_INC: '☀↑'
    LA(LEFT): ↞
    LA(RIGHT): ↠
    LG(LEFT): ⇤
    LG(RIGHT): ⇥
    LC(C): "COPY"
    LC(Z): "UNDO"
    LC(X): "CUT"
    LC(V): "PASTE"
    LC(Y): "REDO"
    'LS(LC(LG(LALT)))': 'HYPER'
    'RS(RC(RG(RALT)))': 'HYPER'
    'LC(LG(LALT))': 'MEH'
    'RC(RG(RALT))': 'MEH'
    'LG(Q)': '$$material:menu_open$$Q'
    'LG(W)': '$$material:menu_open$$W'
    'LG(GRAVE)': '$$material:menu_open$$`'
    'LG(Z)': '$$material:menu_open$$Z'
    'LG(X)': '$$material:menu_open$$X'
    'LG(C)': '$$material:menu_open$$C'
    'LG(V)': '$$material:menu_open$$V'
    'LC(TAB)': '"CTRL"↹'
    'LS(LC(TAB))': '"CTRL"⇧↹'
#   zmk_combos:
#     combo_tog_nav_word: {'a': 'bottom', 'o': -0.25}
#     combo_tog_num_word: {'a': 'bottom', 'o': 0.0}
#     combo_return: {'a': 'bottom', 'o': 0.3}
#     combo_capsword: {'k': "Caps\nWord"}
